mysite/myapp/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout
from myapp import views


urlpatterns = patterns('',
    url(r'^create_planned/$', views.create_planned, name='create_planned'),
    url(r'^create_needed/$', views.create_needed, name='create_needed'),
    url(r'^planned/$', views.planned, name="what_is_planned"),
    url(r'^needed/$', views.needed, name="what_is_needed"),
    url(r'^planned_archive/$', views.planned_archive, name="what_was_offered"),
    url(r'^register/$', views.register, name="new_user_register"),
    url(r'^accounts/logout/$', logout, name="user_logout"),
    url(r'^myapp/login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^myapp/changeprofile/$', views.changeuser, name="change_profile"),
    url(r'^myapp/mypostsneeded/$', views.mypostsneeded, name="see_mypost_needed"),
    url(r'^myapp/mypostsscheduled/$', views.mypostsscheduled, name="see_mypost_scheduled"),
)

mysite/trainings/urls.py
from django.conf.urls import patterns, include, url


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'myapp/login.html'}),
    (r'', include('django.contrib.auth.urls')),
    (r'^events/', include('myapp.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'', include('social_auth.urls')),
    (r'^accounts/logout/$', 'django.contrib.auth.views.login', {'template_name': 'myapp/login.html'}),
    url(r'^.*', 'myapp.views.needed'),
)

mysite/myapp/models.py
from django.db import models
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from django.db.models.query import QuerySet



def today():
    now = datetime.now()
    start = datetime.min.replace(year=now.year, month=now.month,
        day=now.day)
    end = (start + timedelta(days=1)) - timedelta.resolution
    return (start, end)


class EventQuerySet(QuerySet):
    def today(self):
        return self.filter(date_class_starts__range=today())


class EventManager(models.Manager):
    def get_query_set(self):
        return EventQuerySet(self.model)

    def today(self):
        return self.get_query_set().today()


class Location(models.Model):
    city = models.CharField(verbose_name="City of Training", max_length=100)
    state = models.CharField(verbose_name="State of Training", max_length=30)
    country = models.CharField(verbose_name="Country of Training", max_length=100, default="United States of America")

    def __unicode__(self):
        return "%s, %s" % (self.city, self.state)


class TrainingDesired(models.Model):
    creator = models.ForeignKey(User)
    title = models.CharField(verbose_name="Title of the training", max_length=200)
    organization = models.CharField(verbose_name="Organization needing", max_length=200, blank=True, null=True)
    creation_date = models.DateTimeField(default=datetime.now)
    description = models.CharField(verbose_name="About this training", max_length=500)
    fullfills = models.CharField(verbose_name="Requirements it will fullfill", max_length=200, blank=True, null=True)
    audience = models.CharField(verbose_name='Who this is for', max_length=200, blank=True, null=True)
    person = models.CharField(verbose_name="Person to contact", max_length=50)
    contact_email = models.EmailField(verbose_name="Contact email", max_length=254, blank=True, null=True)
    contact_phone = models.CharField(verbose_name="Contact phone", max_length=40, blank=True, null=True)
    cost = models.CharField(verbose_name="Thoughts about cost", max_length=200, blank=True, null=True,)
    location = models.ForeignKey(Location)
    visible = models.BooleanField(default=True)

    def __unicode__(self):
        return "%s needed by %s" % (self.title, self.organization)

    class Meta(object):
        verbose_name_plural = 'Trainings Desired'


class TrainingScheduled(models.Model):
    creator = models.ForeignKey(User)
    date_class_starts = models.DateField(verbose_name="Date training starts")
    where = models.CharField(verbose_name="Where training will be held", max_length=150, blank=True, null=True)
    title = models.CharField(verbose_name="Title of the training", max_length=200)
    creation_date = models.DateTimeField(default=datetime.now)
    description = models.CharField(verbose_name="About this training", max_length=500)
    fullfills = models.CharField(verbose_name="Requirements it will fullfill", max_length=200, blank=True, null=True)
    audience = models.CharField(verbose_name='Who this is for', max_length=200, blank=True, null=True)
    person = models.CharField(verbose_name="Person to contact", max_length=50)
    contact_email = models.EmailField(verbose_name="Contact email", max_length=254, blank=True, null=True)
    contact_phone = models.CharField(verbose_name="Contact phone", max_length=40, blank=True, null=True)
    cost = models.CharField(verbose_name="Thoughts about cost", max_length=200, blank=True, null=True,)
    location = models.ForeignKey(Location)
    visible = models.BooleanField(default=True)

    objects = EventManager()

    def __unicode__(self):
        return "%s at %s on %s" % (self.title, self.where, self.date_class_starts)

    class Meta(object):
        verbose_name_plural = 'Trainings Scheduled'

mysite/myapp/forms.py
from django import forms
from myapp.models import TrainingScheduled, TrainingDesired
from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper
from django.contrib.auth.models import User


class ScheduledForm(forms.ModelForm):
    description = forms.CharField(max_length=500, widget=forms.Textarea)
    contact_email = forms.EmailField(max_length=150, required=False)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'ScheduledForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Create Event'))
        super(ScheduledForm, self).__init__(*args, **kwargs)

    class Meta:
        model = TrainingScheduled
        fields = ('title', 'date_class_starts', 'where', 'description', 'fullfills',
                'audience', 'cost', 'person', 'contact_email', 'contact_phone', 'location',)


class WantedForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea)
    contact_email = forms.EmailField(max_length=254, required=False)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'WantedForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Submit Need'))
        super(WantedForm, self).__init__(*args, **kwargs)

    class Meta:
        model = TrainingDesired
        fields = ('title', 'organization', 'description', 'fullfills',
            'audience', 'cost', 'person', 'contact_email', 'contact_phone', 'location',)


class UserChangerForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'UserChangerForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Change Your User Information'))
        super(UserChangerForm, self).__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)

mysite/myapp/views.py
from myapp.models import TrainingScheduled, TrainingDesired
from django.shortcuts import render_to_response
from django.template import RequestContext
from myapp.forms import ScheduledForm, WantedForm, UserChangerForm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from datetime import datetime
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.conf import settings


def planned(request):
    now = datetime.now()
    events = TrainingScheduled.objects.filter(date_class_starts__gte=now.date()).filter(visible=True).order_by('date_class_starts')
    rt = settings.RANDOM_TIP()
    messages.add_message(request, messages.INFO, rt)
    context = {
        'events': events,
    }
    return render_to_response(
        'myapp/future.html',
        context,
        context_instance=RequestContext(request),
    )


def needed(request):
    events = TrainingDesired.objects.filter(visible=True).order_by('-creation_date')
    rt = settings.RANDOM_TIP()
    messages.add_message(request, messages.INFO, rt)
    context = {
        'events': events,
    }
    return render_to_response(
        'myapp/needed.html',
        context,
        context_instance=RequestContext(request),
    )


def create_planned(request):
    if request.user.is_authenticated():
        z = 1
    else:
        msgtxt = 'You are not logged in.  Which is fine.  You can still post.  But, you will not be able to easily delete or edit your posts later.  ' + '<a href="' + reverse('login') + '">Log in</a>' + ' | ' + '<a href="' + reverse('new_user_register') + '">New Account</a>'
        messages.add_message(request, messages.WARNING,  msgtxt, extra_tags='safe')
    form = ScheduledForm(request.POST or None)
    if form.is_valid():
        x = form.save(commit=False)
        if request.user.is_authenticated():
            x.creator = request.user
        else:
            x.creator = User.objects.get(username__exact='anonymous')
        x.save()
        messages.add_message(request, messages.SUCCESS, 'Your event was posted.  Events are listed in chronological order, so yours may not be at the top.')
        if 'next' in request.POST:
            next = request.POST['next']
        else:
            next = reverse('what_is_planned')
        return HttpResponseRedirect(next)
    return render_to_response(
        'myapp/create_planned.html',
        {'form': form},
        context_instance=RequestContext(request),
    )


def create_needed(request):
    if request.user.is_authenticated():
        z = 1
    else:
        msgtxt = 'You are not logged in.  Which is fine.  You can still post.  But, you will not be able to easily delete or edit your posts later.  ' + '<a href="' + reverse('login') + '">Log in</a>' + ' | ' + '<a href="' + reverse('new_user_register') + '">New Account</a>'
        messages.add_message(request, messages.WARNING,  msgtxt, extra_tags='safe')
    form = WantedForm(request.POST or None)
    if form.is_valid():
        x = form.save(commit=False)
        if request.user.is_authenticated():
            x.creator = request.user
        else:
            x.creator = User.objects.get(username__exact='anonymous')
        x.save()
        messages.add_message(request, messages.SUCCESS, 'Your training need was posted.')
        if 'next' in request.POST:
            next = request.POST['next']
        else:
            next = reverse('what_is_needed')
        return HttpResponseRedirect(next)
    return render_to_response(
        'myapp/create_needed.html',
        {'form': form},
        context_instance=RequestContext(request),
    )


def planned_archive(request):
    now = datetime.now()
    events = TrainingScheduled.objects.filter(date_class_starts__lt=now.date()).filter(visible=True).order_by('date_class_starts')
    context = {
        'events': events,
    }
    return render_to_response(
        'myapp/archive_of_past_plans.html',
        context,
        context_instance=RequestContext(request),
    )


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.save()
            next = reverse('login')
            return HttpResponseRedirect(next)
    else:
        form = UserCreationForm()
    return render_to_response(
        'registration/register.html',
        {'form': form, },
        context_instance=RequestContext(request),
    )


@login_required
def changeuser(request):
    form = UserChangerForm(request.POST or None)
    if form.is_valid():
        x = form.save(commit=False)
        if request.user.is_authenticated():
            x.creator = User.objects.get
            x.save()
            messages.add_message(request, messages.SUCCESS, 'Your user information was saved.')
        else:
            messages.add_message(request, messages.ERROR, 'Your user information was not saved.')
        if 'next' in request.POST:
            next = request.POST['next']
        else:
            next = reverse('what_is_needed')
        return HttpResponseRedirect(next)
    return render_to_response(
        'registration/changeuser.html',
        {'form': form},
        context_instance=RequestContext(request),
    )


@login_required
def mypostsneeded(request):
    me = request.user
    events = TrainingDesired.objects.filter(visible=True).filter(creator=me).order_by('-creation_date')
    rt = settings.RANDOM_TIP()
    messages.add_message(request, messages.INFO, rt)
    context = {
        'events': events,
    }
    return render_to_response(
        'myapp/mypostsneeded.html',
        context,
        context_instance=RequestContext(request),
    )


@login_required
def mypostsscheduled(request):
    me = request.user
    events = TrainingScheduled.objects.filter(visible=True).filter(creator=me).order_by('-creation_date')
    rt = settings.RANDOM_TIP()
    messages.add_message(request, messages.INFO, rt)
    context = {
        'events': events,
    }
    return render_to_response(
        'myapp/mypostsscheduled.html',
        context,
        context_instance=RequestContext(request),
    )

mysite/trainings/templates/myapp/archive_of_past_plans.html
{% extends "base.html" %}

{% block title %}Archive of Past Plans - {{ block.super}}{% endblock %}

{% block main_content %}



    <div class="hero-unit">
        <h3>The trainings that were offered in the past.</h3>
        <p>Archive of trainings shared so far. </p>
        
      </div>



<script type="text/javascript">
    $(function () {
        $('body').popover({
            selector: '[data-toggle="popover"]',
            html : true,
        });

        $('body').tooltip({
            selector: 'a[rel="tooltip"], [data-toggle="tooltip"]'
        });
    });
</script>


{% if messages %}
   <div class="bs-docs-example">
    {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <button type="button" class="close" data-dismiss="alert">&times;</button>
             {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
            </div>
    {% endfor %}
          </div>
{% endif %}





    {% if events %}

    <div class="row">
        
        {% for events in events %}
   
                <div class="span4"> <div class="well">
                    
        <p><h4>{{ events.title }}</h4></p>
         <p>{{ events.description }}</p>
         <p>{{ events.audience }}</p>
                    <div class="btn btn-mini btn-primary" data-toggle="popover" data-placement="btm" data-content="
             {% if events.title %}<strong>Title: </strong>{{ events.title }}<br>{% endif %}
             {% if events.date_class_starts %}<strong>Date Starts: </strong>{{ events.date_class_starts }}<br>{% endif %}
             {% if events.where %}<strong>Where: </strong>{{ events.where }}<br>{% endif %}
             {% if events.description %}<strong>Description: </strong>{{ events.description }}<br>{% endif %}
             {% if events.fullfills %}<strong>Requirements To Be Met: </strong>{{ events.fullfills }}<br>{% endif %}
             {% if events.audience %}<strong>Audience: </strong>{{ events.audience }}<br>{% endif %}
             {% if events.cost %}<strong>Cost: </strong>{{ events.cost }}<br>{% endif %}
             {% if events.person %}<strong>Contact: </strong>{{ events.person }}<br>{% endif %}
             {% if events.contact_email %}<strong>Email: </strong>{{ events.contact_email }}<br>{% endif %}
             {% if events.contact_phone %}<strong>Phone: </strong>{{ events.contact_phone }}<br>{% endif %}
             ">details</div>
     </div>
          </div>
        {% endfor %}
         </div>
        
    {% else %}
        <p>Nothing scheduled yet.</p>
    {% endif %}


    
{% endblock %}

mysite/trainings/templates/myapp/create_needed.html
 {% extends "base.html" %}

 {% block title %}Express a Training Need - {{ block.super}}{% endblock %}

{% block extra_head %}
 <script>
$(function() {
var availableTags = [
"Green Dot",
"CPR",
"First Aid",
"HAZCOM Hazard Communication (MSDS)",
"Title 10",
"Workplace Violence",
"SART",
"Fire Extinguishers",
"Bloodborne Pathogens",
"Workplace Harassment",
"Teambuilding",
"Office Ergonomics",
"Fair Labor Standards Act (FLSA)",
"FMLA",
"New Employee Orientation",
"Workplace Privacy",
"Sexual Harassment",
"Stress Management",
"Workers' Compensation",
"Conflict Resolution",
"Laboratory Safety Training",
"PPE",
"Stormwater Pollution Prevention",
"Universal Waste Training - Large and Small Quantity Handlers",
"Back Safety Training",
"Handling Objections",
"Setting Goals",
"Pandemic Flu- How to Prevent and Respond",
"Electrical Safety for Healthcare Workers",
"Ergonomics for Healthcare Workers",
"Respiratory Protection for Healthcare Workers",
"Preventing Slips, Trips, and Falls for Healthcare Workers",
"Violence Prevention for Healthcare and Social Service Workers",
"Handling Medical Waste",
"Lifting and Carrying Patients Best Practices",
"HIPAA Privacy Laws",
"Microsoft Access",
"Microsoft Excel",
"Microsoft Word",
"Microsoft PowerPoint",
"Grant Writing",
"Budget Formulation",
"Statistics",
"Audits",
"Grants Management",
"Human Resource Development",
"Agile Project Management",
"Quickbooks",
"Governance",
"Customer Service",
];
$( "#id_title" ).autocomplete({
source: availableTags
});
});
</script>
{% endblock %}




{% load crispy_forms_tags %}
 {% block main_content %}

<div class="row"> <div class="span12"> <div class="well well-small">
  <H4> This is for adding training you, or your organization, want/need to have, but don't have scheduled yet.  
    If you want the opposite, <a href="{% url create_planned %}">click</a>.</H4>
     </div>     </div>  </div>

<div class="row">
      <div class="bs-docs-example" >
        <div class="span12">

           {% if messages %}
   <div class="bs-docs-example">
    {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <button type="button" class="close" data-dismiss="alert">&times;</button>
             {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
            </div>
    {% endfor %}
          </div>
{% endif %}

          </div>
        </div>

     </div>





{% crispy form %}

 {% endblock %}

mysite/trainings/templates/myapp/create_planned.html
 {% extends "base.html" %}

 {% block title %}Create - {{ block.super}}{% endblock %}

{% block extra_head %}
<script>
$(function() {
var availableTags = [
"Green Dot",
"CPR",
"First Aid",
"HAZCOM Hazard Communication (MSDS)",
"Title 10",
"Workplace Violence",
"SART",
"Fire Extinguishers",
"Bloodborne Pathogens",
"Workplace Harassment",
"Teambuilding",
"Office Ergonomics",
"Fair Labor Standards Act (FLSA)",
"FMLA",
"New Employee Orientation",
"Workplace Privacy",
"Sexual Harassment",
"Stress Management",
"Workers' Compensation",
"Conflict Resolution",
"Laboratory Safety Training",
"PPE",
"Stormwater Pollution Prevention",
"Universal Waste Training - Large and Small Quantity Handlers",
"Back Safety Training",
"Handling Objections",
"Setting Goals",
"Pandemic Flu- How to Prevent and Respond",
"Electrical Safety for Healthcare Workers",
"Ergonomics for Healthcare Workers",
"Respiratory Protection for Healthcare Workers",
"Preventing Slips, Trips, and Falls for Healthcare Workers",
"Violence Prevention for Healthcare and Social Service Workers",
"Handling Medical Waste",
"Lifting and Carrying Patients Best Practices",
"HIPAA Privacy Laws",
"Microsoft Access",
"Microsoft Excel",
"Microsoft Word",
"Microsoft PowerPoint",
"Grant Writing",
"Budget Formulation",
"Statistics",
"Audits",
"Grants Management",
"Human Resource Development",
"Agile Project Management",
"Quickbooks",
"Governance",
"Customer Service",
];
$( "#id_title" ).autocomplete({
source: availableTags
});
});
</script>

 <script>
$(function() {
$( "#id_date_class_starts" ).datepicker();
});
</script>
{% endblock %}

{% load crispy_forms_tags %}
 {% block main_content %}

<div class="row"> <div class="span12"> <div class="well well-small">
  <H4> This is for adding training you, or your organization, have already scheduled.  You are posting it here becuase you want to invite others in the community to attend. 
  If you want to do the opposite, <a href="{% url create_needed %}">click</a> .</H4>
     </div>     </div>  </div>


<div class="row">
      <div class="bs-docs-example" >
        <div class="span12">

           {% if messages %}
   <div class="bs-docs-example">
    {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <button type="button" class="close" data-dismiss="alert">&times;</button>
             {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
            </div>
    {% endfor %}
          </div>
{% endif %}

          </div>
        </div>

     </div>



{% crispy form %}


 {% endblock %}

mysite/trainings/templates/myapp/future.html
{% extends "base.html" %}

{% block title %}Planned Trainings - {{ block.super}}{% endblock %}



{% block main_content %}



    <div class="hero-unit">
        <h3>Share Training With Other Organizations</h3>
        <p>Scheduled training coming up in the community.</p>
        
      </div>


<script type="text/javascript">
    $(function () {
        $('body').popover({
            selector: '[data-toggle="popover"]',
            html : true,
            placement: "bottom",
        });

        $('body').tooltip({
            selector: 'a[rel="tooltip"], [data-toggle="tooltip"]'
        });
    });
</script>


<div class="row">
<div class="span2"> <div class="well well-small">
<a class="btn" type="button" href="{% url create_planned %}">ADD <i class="icon-pencil"></i><i class="icon-calendar"></i></a>

     </div>
</div>

<div class="row">
      <div class="bs-docs-example" >
        <div class="span10">

          {% if messages %}
   <div class="bs-docs-example">
    {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <button type="button" class="close" data-dismiss="alert">&times;</button>
             {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
            </div>
    {% endfor %}
          </div>
{% endif %}

          </div>
        </div>

     </div>


</div>
    {% if events %}

   <div class="row" id="draggable">
        
        {% for events in events %}
   
                <div class="span4"> <div class="well well-small">
                    
        <p><h4>{{ events.title }}</h4></p>
         <p>{{ events.description }}</p>
         <p>{{ events.audience }}</p>
         <p>{{ events.date_class_starts }}</p>
         <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <div class="btn btn-mini btn-primary" data-toggle="popover" data-placement="btm" data-content="
             {% if events.title %}<strong>Title: </strong>{{ events.title }}<br>{% endif %}
             {% if events.date_class_starts %}<strong>Date Starts: </strong>{{ events.date_class_starts }}<br>{% endif %}
             {% if events.where %}<strong>Where: </strong>{{ events.where }}<br>{% endif %}
             {% if events.description %}<strong>Description: </strong>{{ events.description }}<br>{% endif %}
             {% if events.fullfills %}<strong>Requirements To Be Met: </strong>{{ events.fullfills }}<br>{% endif %}
             {% if events.audience %}<strong>Audience: </strong>{{ events.audience }}<br>{% endif %}
             {% if events.cost %}<strong>Cost: </strong>{{ events.cost }}<br>{% endif %}
             {% if events.person %}<strong>Contact: </strong>{{ events.person }}<br>{% endif %}
             {% if events.contact_email %}<strong>Email: </strong>{{ events.contact_email }}<br>{% endif %}
             {% if events.contact_phone %}<strong>Phone: </strong>{{ events.contact_phone }}<br>{% endif %}
             ">details</div>
     </div>
          </div>
        {% endfor %}
         </div>
        
    {% else %}
        <p>Nothing scheduled yet.</p>
    {% endif %}

       
{% endblock %}

mysite/trainings/templates/myapp/login.html
{% extends "base.html" %}
{% load url from future %}
{% block main_content %}

{% if messages %}
   <div class="bs-docs-example">
    {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <button type="button" class="close" data-dismiss="alert">&times;</button>
             {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
            </div>
    {% endfor %}
          </div>
{% endif %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="">{% csrf_token %}
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

mysite/trainings/templates/myapp/mypostsneeded.html
{% extends "base.html" %}

{% block title %}My Posts of Training Needs - {{ block.super}}{% endblock %}





{% block main_content %}







<script type="text/javascript">
    $(function () {
        $('body').popover({
            selector: '[data-toggle="popover"]',
            html : true,
            placement: "bottom",
        });

        $('body').tooltip({
            selector: 'a[rel="tooltip"], [data-toggle="tooltip"]'
        });
    });
</script>







<div class="row">
      <div class="bs-docs-example" >
        <div class="span12">

           {% if messages %}
   <div class="bs-docs-example">
    {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <button type="button" class="close" data-dismiss="alert">&times;</button>
             {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
            </div>
    {% endfor %}
          </div>
{% endif %}

          </div>
        </div>






    {% if events %}

        {% for events in events %}

        <div class="row">
   
             <div class="span12"> <div class="well well-small">
                    
            {% if events.title %}<strong>Title: </strong>{{ events.title }}<br>{% endif %}
             {% if events.organization %}<strong>Organization Needing: </strong>{{ events.organization }}<br>{% endif %}
             {% if events.description %}<strong>Description: </strong>{{ events.description }}<br>{% endif %}
             {% if events.fullfills %}<strong>Requirements To Be Met: </strong>{{ events.fullfills }}<br>{% endif %}
             {% if events.audience %}<strong>Audience: </strong>{{ events.audience }}<br>{% endif %}
             {% if events.cost %}<strong>Cost: </strong>{{ events.cost }}<br>{% endif %}
             {% if events.person %}<strong>Contact: </strong>{{ events.person }}<br>{% endif %}
             {% if events.contact_email %}<strong>Email: </strong>{{ events.contact_email }}<br>{% endif %}
             {% if events.contact_phone %}<strong>Phone: </strong>{{ events.contact_phone }}<br>{% endif %}
      

     </div>
          </div>

</div>
        {% endfor %}
         
    {% else %}
        <p>Nothing here yet.</p>
    {% endif %}


     
{% endblock %}